"use client";
import {useRef,useState} from "react";
import {MathVisual} from "@/components/MathVisuals";
import {generateLesson,scanGeminiModels,type GeminiModel} from "@/lib/gemini-client";
import type {Lesson} from "@/lib/types";
import {auditLesson,type AuditItem} from "@/lib/audit";
import {readSource,type SourceDoc} from "@/lib/importer";
import {exportPptx} from "@/lib/exporters";

type FormData={teacher:string;school:string;grade:string;book:string;lesson:string;periods:string;students:string;slideCount:string;style:string;notes:string};
const initial:FormData={teacher:"Nguyễn Văn A",school:"Trường THPT ...",grade:"Toán 10",book:"Kết nối tri thức",lesson:"",periods:"2",students:"Trung bình - khá",slideCount:"30",style:"Xanh học thuật",notes:""};

export default function Page(){
 const [form,setForm]=useState(initial),[lesson,setLesson]=useState<Lesson|null>(null),[documents,setDocuments]=useState<SourceDoc[]>([]),[jsonFile,setJsonFile]=useState<SourceDoc|null>(null),[apiKey,setApiKey]=useState(""),[models,setModels]=useState<GeminiModel[]>([]),[model,setModel]=useState("auto"),[message,setMessage]=useState("Sẵn sàng"),[busy,setBusy]=useState(false),[audit,setAudit]=useState<AuditItem[]>([]),[includeAnswers,setIncludeAnswers]=useState(true),[teacherNotes,setTeacherNotes]=useState(true);
 const previewRef=useRef<HTMLElement>(null);
 const set=(key:keyof FormData)=>(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm(f=>({...f,[key]:e.target.value}));
 async function scan(){if(!apiKey.trim()){setMessage("Vui lòng dán khóa API Gemini");return []}try{const found=await scanGeminiModels(apiKey.trim());setModels(found);if(found[0])setModel(found[0].name);setMessage(`Đã kết nối ${found.length} mô hình`);return found}catch(e){setMessage(e instanceof Error?e.message:"Không kiểm tra được khóa");return []}}
 async function importSources(list:FileList|null){if(!list)return;setBusy(true);try{const added:SourceDoc[]=[];for(const file of Array.from(list).slice(0,8-documents.length))added.push(await readSource(file));setDocuments(x=>[...x,...added]);setMessage(`Đã đọc ${added.length} tài liệu`)}catch(e){setMessage(e instanceof Error?e.message:"Không đọc được tài liệu")}finally{setBusy(false)}}
 async function importJson(list:FileList|null){const file=list?.[0];if(!file)return;try{const doc=await readSource(file);const parsed=JSON.parse(doc.text) as Lesson;setJsonFile(doc);setLesson(parsed);setAudit(auditLesson(parsed));setMessage("Đã nạp bài giảng JSON") }catch{setMessage("File JSON không đúng cấu trúc LessonStudio V10")}}
 async function generate(){if(!form.lesson.trim()){setMessage("Hãy nhập tên bài");return}if(!apiKey.trim()){setMessage("Hãy dán khóa API Gemini");return}setBusy(true);setMessage("AI đang xây dựng nội dung slide…");try{let chosen=model;if(chosen==="auto"){const found=await scan();if(!found.length)throw new Error("Không tìm thấy mô hình Gemini phù hợp");chosen=found[0].name}const context=documents.map((d,i)=>`[TÀI LIỆU ${i+1}: ${d.name}]\n${d.text}`).join("\n\n").slice(0,180000);const prompt=`Tạo bài giảng PowerPoint môn Toán cho ${form.grade}, bộ sách ${form.book}, bài "${form.lesson}", thời lượng ${form.periods} tiết, khoảng ${form.slideCount} slide. Đối tượng học sinh: ${form.students}. Chỉ tạo nội dung trình chiếu, không tạo giáo án hay kế hoạch bài dạy. Có kiến thức trọng tâm, ví dụ, câu hỏi luyện tập${includeAnswers?" và đáp án/gợi ý":""}. Khi phù hợp phải có bảng biến thiên, bảng xét dấu và đồ thị đúng dữ liệu. Yêu cầu thêm: ${form.notes}.${context?`\n\nNGUỒN:\n${context}`:""}`;const data=await generateLesson(apiKey.trim(),chosen,prompt,form.style);setLesson(data);const report=auditLesson(data);setAudit(report);setMessage(report.some(x=>x.level==="error")?"Nội dung còn lỗi cần kiểm tra":"Bài giảng đã sẵn sàng để xuất PowerPoint")}catch(e){setMessage(e instanceof Error?e.message:"Có lỗi xảy ra")}finally{setBusy(false)}}
 async function exportDeck(){if(!lesson||!previewRef.current)return;const report=auditLesson(lesson);setAudit(report);if(report.some(x=>x.level==="error")){setMessage("Chưa thể xuất vì dữ liệu hình Toán còn lỗi");return}setBusy(true);try{await exportPptx(previewRef.current,lesson,{teacher:form.teacher,school:form.school});setMessage("Đã xuất PowerPoint bài giảng")}catch(e){setMessage(e instanceof Error?e.message:"Không xuất được PowerPoint")}finally{setBusy(false)}}
 return <main className="v9-app"><aside className="v9-sidebar">
  <section><small>Chế độ làm việc</small><label className="radio active"><input type="radio" checked readOnly/> 🔴 Tạo bài giảng PowerPoint</label><label className="radio disabled"><input type="radio" disabled/> 🖼 Xuống Ảnh + HTML</label><label className="radio disabled"><input type="radio" disabled/> 🏭 AI Exam Factory V5.0</label><label className="radio disabled"><input type="radio" disabled/> 🧾 Exam Intelligence V5.0</label><label className="radio disabled"><input type="radio" disabled/> Thẩm định đề Toán Pro</label><label className="radio disabled"><input type="radio" disabled/> Thẩm định đề Toán 360°</label></section>
  <h3>Thông tin bài dạy</h3><label>Tên giáo viên<input value={form.teacher} onChange={set("teacher")}/></label><label>Trường<input value={form.school} onChange={set("school")}/></label><label>Khối lớp<select value={form.grade} onChange={set("grade")}><option>Toán 10</option><option>Toán 11</option><option>Toán 12</option></select></label><label>Bộ sách<select value={form.book} onChange={set("book")}><option>Kết nối tri thức</option><option>Chân trời sáng tạo</option><option>Cánh Diều</option></select></label><label>Tên bài<input value={form.lesson} onChange={set("lesson")} placeholder="Có thể để trống để AI xác định"/></label><label>Số tiết<input type="number" min="1" max="12" value={form.periods} onChange={set("periods")}/></label><label>Đối tượng học sinh<select value={form.students} onChange={set("students")}><option>Trung bình - khá</option><option>Cơ bản</option><option>Khá - giỏi</option><option>Ôn thi TN THPT</option></select></label><label>Số slide dự kiến <b>{form.slideCount}</b><input className="range" type="range" min="10" max="60" value={form.slideCount} onChange={set("slideCount")}/></label><label>Phong cách<select value={form.style} onChange={set("style")}><option>Xanh học thuật</option><option>Hiện đại tối giản</option><option>Tươi sáng lớp học</option></select></label><label className="check"><input type="checkbox" checked={includeAnswers} onChange={e=>setIncludeAnswers(e.target.checked)}/> Đưa đáp án/gợi ý vào slide</label><label className="check"><input type="checkbox" checked={teacherNotes} onChange={e=>setTeacherNotes(e.target.checked)}/> Tạo ghi chú dành cho giáo viên</label>
  <div className="key-box"><label>🔑 Khóa API Gemini<input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="Dán khóa API miễn phí"/></label><div><select value={model} onChange={e=>setModel(e.target.value)}><option value="auto">Tự động chọn mô hình</option>{models.map(m=><option key={m.name} value={m.name}>{m.displayName||m.name}</option>)}</select><button onClick={scan}>Dò</button></div></div>
 </aside><section className="v9-main" ref={previewRef}><header><div className="triangle">◩</div><div><h1>Trợ lý soạn PowerPoint Toán THPT</h1><p>Phiên bản 10.0 · PowerPoint chuyên nghiệp · MathViz · Chống tràn chữ</p></div></header>
  {!lesson?<div className="start-screen"><h2>1. Tải tài liệu nguồn</h2><p>PDF, Word, TXT hoặc JSON (tối đa 8 tệp, tổng 50 MB)</p><label className="upload"><input type="file" multiple accept=".pdf,.docx,.txt,.md,.json" onChange={e=>importSources(e.target.files)}/><span>⇧ &nbsp; Upload</span><small>200MB per file · PDF, DOCX, TXT, JSON</small></label>{documents.length>0&&<div className="file-list">{documents.map((d,i)=><span key={i}>✓ {d.name}</span>)}</div>}<p className="hint">Nên dùng tài liệu chính thống: SGK, SGV, kế hoạch bài dạy hoặc chuyên đề đã kiểm duyệt.</p><h2>2. LessonStudio V10.0 · Visual Specification PowerPoint</h2><p>Nhận JSON bài giảng hoặc JSON ngân hàng câu hỏi, tự dựng công thức và hình Toán.</p><label className="upload"><input type="file" accept=".json" onChange={e=>importJson(e.target.files)}/><span>⇧ &nbsp; Upload JSON</span><small>{jsonFile?.name||"JSON bài giảng · JSON ngân hàng câu hỏi"}</small></label><textarea value={form.notes} onChange={set("notes")} placeholder="Yêu cầu riêng cho bài giảng..."/><button className="create" onClick={generate} disabled={busy}>🚀 {busy?"ĐANG TẠO BÀI GIẢNG…":"TẠO POWERPOINT BÀI GIẢNG"}</button></div>:<div className="deck-preview"><div className="preview-toolbar"><div><small>BÀI GIẢNG POWERPOINT</small><h2>{lesson.title}</h2></div><button onClick={exportDeck} disabled={busy}>⬇ XUẤT POWERPOINT</button></div>{audit.some(x=>x.level==="error")&&<div className="audit-box">{audit.filter(x=>x.level==="error").map((a,i)=><p className="error" key={i}>{a.message}</p>)}</div>}{lesson.sections.map((s,i)=><article key={i}><h3><em>{String(i+1).padStart(2,"0")}</em>{s.heading}</h3><p>{s.content}</p><div className="visual-grid">{s.visuals?.map((v,j)=><div className={`visual-card ${v.type}`} key={j}><MathVisual visual={v}/></div>)}</div></article>)}</div>}
 </section><div className="v9-status">{message}</div></main>
}
