"use client";
import {useMemo,useState} from "react";
import {MathVisual} from "@/components/MathVisuals";
import {generateLesson,scanGeminiModels,type GeminiModel} from "@/lib/gemini-client";
import {sampleLesson} from "@/lib/sample";
import type {Lesson} from "@/lib/types";

export default function Page(){
 const [source,setSource]=useState(JSON.stringify(sampleLesson,null,2)),[prompt,setPrompt]=useState("Tạo bài giảng Toán 12 về khảo sát hàm số, có công thức, bảng biến thiên, bảng xét dấu và đồ thị."),[lesson,setLesson]=useState<Lesson>(sampleLesson),[message,setMessage]=useState("Visual Contract hợp lệ"),[busy,setBusy]=useState(false),[apiKey,setApiKey]=useState(""),[showKey,setShowKey]=useState(false),[style,setStyle]=useState("Đầy đủ, chi tiết"),[models,setModels]=useState<GeminiModel[]>([]),[model,setModel]=useState("auto"),[modelStatus,setModelStatus]=useState("Nhập khóa API để hệ thống tự dò mô hình đang hoạt động.");
 const parsed=useMemo(()=>{try{return JSON.parse(source) as Lesson}catch{return null}},[source]);
 function render(){if(!parsed){setMessage("JSON chưa hợp lệ");return}setLesson(parsed);setMessage("Đã dựng lại bài giảng từ Visual Specification")}
 async function scan(){if(!apiKey.trim()){setModelStatus("Vui lòng dán khóa API Gemini.");return []}setModelStatus("Đang kiểm tra khóa và dò mô hình…");try{const found=await scanGeminiModels(apiKey.trim());if(!found.length)throw new Error("Khóa này chưa có mô hình phù hợp");setModels(found);setModel(found[0].name);setModelStatus(`Kết nối thành công · tìm thấy ${found.length} mô hình`);return found}catch(e){setModels([]);setModel("auto");setModelStatus(e instanceof Error?e.message:"Không kiểm tra được khóa");return []}}
 async function generate(){if(!apiKey.trim()){setMessage("Hãy dán khóa API Gemini trước khi soạn");return}setBusy(true);setMessage("AI đang tạo Visual Specification…");try{let chosen=model;if(chosen==="auto"){const found=await scan();if(!found.length)throw new Error("Không tìm thấy mô hình Gemini phù hợp");chosen=found[0].name}const data=await generateLesson(apiKey.trim(),chosen,prompt,style);setLesson(data);setSource(JSON.stringify(data,null,2));setMessage("Đã tạo và kiểm tra cấu trúc hình Toán")}catch(e){setMessage(e instanceof Error?e.message:"Có lỗi xảy ra")}finally{setBusy(false)}}
 function clearKey(){setApiKey("");setShowKey(false);setModels([]);setModel("auto");setModelStatus("Đã xóa khóa khỏi phiên trình duyệt.")}
 return <main><header><div className="brand">LS</div><div><h1>LessonStudio <span>V10</span></h1><p>Visual Specification · Toán THPT</p></div><div className="status">● {message}</div></header><div className="workspace"><aside>
 <details className="key-panel" open><summary>Kết nối Gemini bằng khóa API <small>để AI đọc sâu tài liệu và soạn bài tự động</small></summary><div className="key-body"><ol><li>Bấm <a href="https://aistudio.google.com/app/apikey" target="_blank" rel="noreferrer">lấy mã miễn phí tại đây ↗</a>, đăng nhập bằng tài khoản Google.</li><li>Bấm <b>“Create API key”</b>, rồi sao chép mã.</li><li>Dán mã vừa sao chép vào ô bên dưới.</li></ol><label className="field-label">Khóa API Gemini – thông tin bí mật</label><div className="key-row"><input value={apiKey} onChange={e=>setApiKey(e.target.value)} type={showKey?"text":"password"} autoComplete="off" placeholder="Dán khóa API từ Google AI Studio"/><button type="button" onClick={()=>setShowKey(v=>!v)}>{showKey?"Ẩn":"Hiện"}</button><button type="button" onClick={clearKey}>Xóa</button></div><label className="field-label">Phong cách bài soạn</label><select value={style} onChange={e=>setStyle(e.target.value)}><option>Đầy đủ, chi tiết</option><option>Gọn, dễ triển khai</option><option>Tích cực, sáng tạo</option></select><p className="privacy">Khóa API chỉ tồn tại trong ô nhập của phiên trình duyệt, được gửi trực tiếp đến Google và không được lưu trong bản nháp. Mỗi lần mở lại phần mềm, giáo viên cần dán lại khóa.</p><details className="advanced"><summary>Tùy chọn nâng cao <small>không bắt buộc</small></summary><label className="field-label">Mô hình AI</label><div className="model-row"><select value={model} onChange={e=>setModel(e.target.value)}><option value="auto">Tự động dò mô hình phù hợp (Khuyên dùng)</option>{models.map(m=><option key={m.name} value={m.name}>{m.displayName||m.name.replace("models/","")}</option>)}</select><button type="button" onClick={scan}>Dò lại</button></div><p className="model-status">{modelStatus}</p></details></div></details>
 <div className="step">01 · YÊU CẦU BÀI GIẢNG</div><textarea className="prompt" value={prompt} onChange={e=>setPrompt(e.target.value)}/><button className="primary" onClick={generate} disabled={busy}>{busy?"Đang soạn…":"✦ Soạn bằng AI"}</button><div className="divider"/><div className="step">02 · VISUAL SPECIFICATION</div><textarea className="json" spellCheck={false} value={source} onChange={e=>setSource(e.target.value)}/><button onClick={render}>Dựng lại từ JSON</button><p className="hint">Công thức dùng LaTeX. Hình được dựng bởi phần mềm, không phụ thuộc ảnh AI.</p></aside>
 <section className="preview"><div className="preview-head"><div><small>BẢN XEM TRƯỚC</small><h2>{lesson.title}</h2></div><span>{lesson.subject} · Lớp {lesson.grade}</span></div>{lesson.sections.map((s,i)=><article key={i}><h3><em>{String(i+1).padStart(2,"0")}</em>{s.heading}</h3><p>{s.content}</p><div className="visual-grid">{s.visuals?.map((v,j)=><div className={`visual-card ${v.type}`} key={j}><label>{({formula:"Công thức",variation_table:"Bảng biến thiên",sign_chart:"Bảng xét dấu",graph:"Đồ thị"} as const)[v.type]}</label><MathVisual visual={v}/></div>)}</div></article>)}</section></div></main>}
