"use client";
import {useMemo,useRef,useState} from "react";
import {MathVisual} from "@/components/MathVisuals";
import {generateLesson,scanGeminiModels,type GeminiModel} from "@/lib/gemini-client";
import {sampleLesson} from "@/lib/sample";
import type {Lesson} from "@/lib/types";
import {auditLesson,type AuditItem} from "@/lib/audit";
import {readSource,type SourceDoc} from "@/lib/importer";
import {exportDocx,exportPdf,exportPptx} from "@/lib/exporters";

type FormData={subject:string;grade:string;lesson:string;book:string;periods:string;students:string;classSize:string;equipment:string;tableLayout:string;assessment:string;template:string;sourceMode:string;notes:string};
const emptyForm:FormData={subject:"",grade:"",lesson:"",book:"",periods:"",students:"",classSize:"",equipment:"",tableLayout:"5 cột – chi tiết chuyên môn",assessment:"Tạo bảng kiểm/rubric phù hợp",template:"Tự nhận diện theo môn",sourceMode:"Bám nguồn, cho phép AI đề xuất có nhãn",notes:""};

export default function Page(){
 const [form,setForm]=useState<FormData>(emptyForm),[lesson,setLesson]=useState<Lesson|null>(null),[source,setSource]=useState(JSON.stringify(sampleLesson,null,2)),[message,setMessage]=useState("Sẵn sàng"),[busy,setBusy]=useState(false),[apiKey,setApiKey]=useState(""),[showKey,setShowKey]=useState(false),[style,setStyle]=useState("Đầy đủ, chi tiết"),[models,setModels]=useState<GeminiModel[]>([]),[model,setModel]=useState("auto"),[modelStatus,setModelStatus]=useState("Nhập khóa API để hệ thống tự dò mô hình đang hoạt động."),[documents,setDocuments]=useState<SourceDoc[]>([]),[audit,setAudit]=useState<AuditItem[]>([]),[exporting,setExporting]=useState("");
 const previewRef=useRef<HTMLElement>(null),parsed=useMemo(()=>{try{return JSON.parse(source) as Lesson}catch{return null}},[source]);
 const set=(key:keyof FormData)=>(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm(f=>({...f,[key]:e.target.value}));
 function fillSample(){setForm({subject:"Toán",grade:"12",lesson:"Khảo sát sự biến thiên và vẽ đồ thị của hàm số",book:"Chân trời sáng tạo",periods:"2",students:"Trung bình–khá",classSize:"45",equipment:"TV, bảng phụ, điện thoại theo nhóm",tableLayout:"5 cột – chi tiết chuyên môn",assessment:"Tạo bảng kiểm/rubric phù hợp",template:"Toán học",sourceMode:"Bám nguồn, cho phép AI đề xuất có nhãn",notes:"Ưu tiên hoạt động học tích cực và câu hỏi phân hóa."})}
 async function scan(){if(!apiKey.trim()){setModelStatus("Vui lòng dán khóa API Gemini.");return []}setModelStatus("Đang kiểm tra khóa và dò mô hình…");try{const found=await scanGeminiModels(apiKey.trim());if(!found.length)throw new Error("Khóa này chưa có mô hình phù hợp");setModels(found);setModel(found[0].name);setModelStatus(`Kết nối thành công · ${found.length} mô hình`);return found}catch(e){setModelStatus(e instanceof Error?e.message:"Không kiểm tra được khóa");return []}}
 async function generate(){if(!form.subject||!form.grade||!form.lesson){setMessage("Hãy điền môn học, lớp và tên bài học");return}if(!apiKey.trim()){setMessage("Hãy dán khóa API Gemini");return}setBusy(true);setMessage("AI đang phân tích và soạn kế hoạch…");try{let chosen=model;if(chosen==="auto"){const found=await scan();if(!found.length)throw new Error("Không tìm thấy mô hình Gemini phù hợp");chosen=found[0].name}const context=documents.map((d,i)=>`[NGUỒN ${i+1}: ${d.name}]\n${d.text}`).join("\n\n").slice(0,180000);const prompt=`Soạn KHBD môn ${form.subject}, lớp ${form.grade}, bài ${form.lesson}, bộ sách ${form.book}, ${form.periods||"chưa xác định"} tiết. Học sinh: ${form.students}, sĩ số ${form.classSize}. Thiết bị: ${form.equipment}. Mẫu: ${form.tableLayout}; đánh giá: ${form.assessment}; chuyên môn: ${form.template}; nguồn: ${form.sourceMode}. Yêu cầu thêm: ${form.notes}.${context?`\n\nTÀI LIỆU NGUỒN:\n${context}`:""}`;const data=await generateLesson(apiKey.trim(),chosen,prompt,style);setLesson(data);setSource(JSON.stringify(data,null,2));const report=auditLesson(data);setAudit(report);setMessage(report.some(x=>x.level==="error")?"Còn lỗi cần xử lý":"Bản kế hoạch đã hoàn thành")}catch(e){setMessage(e instanceof Error?e.message:"Có lỗi xảy ra")}finally{setBusy(false)}}
 async function importFiles(list:FileList|null){if(!list)return;setBusy(true);try{const added=[];for(const file of Array.from(list).slice(0,8-documents.length))added.push(await readSource(file));setDocuments(x=>[...x,...added]);setMessage(`Đã đọc ${added.length} tài liệu`)}catch(e){setMessage(e instanceof Error?e.message:"Không đọc được tài liệu")}finally{setBusy(false)}}
 function renderJson(){if(!parsed){setMessage("JSON chưa hợp lệ");return}setLesson(parsed);setAudit(auditLesson(parsed));setMessage("Đã dựng lại từ JSON")}
 function runAudit(){if(!lesson)return;const report=auditLesson(lesson);setAudit(report);setMessage(report.some(x=>x.level==="error")?"Kiểm định phát hiện lỗi chặn xuất":"Kiểm định hoàn tất")}
 async function doExport(kind:"pptx"|"docx"|"pdf"){if(!lesson||!previewRef.current)return;const report=auditLesson(lesson);setAudit(report);if(report.some(x=>x.level==="error")){setMessage("Chưa thể xuất: còn lỗi kiểm định");return}setExporting(kind);try{if(kind==="pptx")await exportPptx(previewRef.current,lesson);if(kind==="docx")await exportDocx(lesson);if(kind==="pdf")await exportPdf(previewRef.current,lesson.title);setMessage(`Đã tạo ${kind.toUpperCase()}`)}finally{setExporting("")}}
 return <main className="app-shell"><header className="topbar"><div className="top-logo">K</div><div><h1>TRỢ LÝ SOẠN GIÁO ÁN</h1><p>CT GDPT 2018 · Năm học 2026–2027 · LessonStudio V10</p></div><button className="theme-button" aria-label="Đổi giao diện">◐</button></header><div className="studio-grid">
 <section className="panel input-panel"><div className="panel-title"><b><i>01</i> Thông tin bài dạy</b><button onClick={fillSample}>Điền dữ liệu mẫu</button></div><div className="form-body"><div className="two"><label>Môn học<input value={form.subject} onChange={set("subject")} placeholder="Ví dụ: Toán"/></label><label>Lớp<input value={form.grade} onChange={set("grade")} placeholder="Từ lớp 6 đến lớp 12"/></label></div><label>Tên bài học<input value={form.lesson} onChange={set("lesson")} placeholder="Ví dụ: Giá trị lớn nhất và giá trị nhỏ nhất của hàm số"/></label><div className="two"><label>Bộ sách<select value={form.book} onChange={set("book")}><option value="">Chọn bộ sách</option><option>Chân trời sáng tạo</option><option>Kết nối tri thức với cuộc sống</option><option>Cánh Diều</option></select></label><label>Số tiết<input value={form.periods} onChange={set("periods")} placeholder="Để trống nếu chưa biết"/></label><label>Đặc điểm học sinh<input value={form.students} onChange={set("students")} placeholder="Ví dụ: Trung bình–khá"/></label><label>Sĩ số<input value={form.classSize} onChange={set("classSize")} placeholder="Ví dụ: 45"/></label></div><label>Thiết bị dạy học<input value={form.equipment} onChange={set("equipment")} placeholder="TV, bảng phụ, điện thoại theo nhóm"/></label><div className="option-box two"><label>Mẫu bảng hoạt động<select value={form.tableLayout} onChange={set("tableLayout")}><option>5 cột – chi tiết chuyên môn</option><option>3 cột – gọn để in</option></select></label><label>Công cụ đánh giá<select value={form.assessment} onChange={set("assessment")}><option>Tạo bảng kiểm/rubric phù hợp</option><option>Chỉ câu hỏi và tiêu chí cơ bản</option></select></label></div><div className="option-box two"><label>Mẫu chuyên môn<select value={form.template} onChange={set("template")}><option>Tự nhận diện theo môn</option><option>Toán học</option><option>STEM/dự án</option></select></label><label>Chế độ sử dụng nguồn<select value={form.sourceMode} onChange={set("sourceMode")}><option>Bám nguồn, cho phép AI đề xuất có nhãn</option><option>Khóa nguồn tuyệt đối</option></select></label></div></div>
 <div className="section-title"><b><i>02</i> Tài liệu nguồn</b><small>Tối đa 8 tệp, 20 MB/tệp</small></div><div className="form-body"><label className="drop-zone"><input type="file" multiple accept=".pdf,.docx,.txt,.md,.json" onChange={e=>importFiles(e.target.files)}/><strong>⇧</strong><b>Kéo thả hoặc bấm để chọn tài liệu</b><span>SGK, SGV, yêu cầu cần đạt, giáo án tham khảo</span></label>{documents.map((d,i)=><div className="source-item" key={i}><span><b>{d.name}</b><small>{Math.ceil(d.size/1024)} KB · đã đọc</small></span><button onClick={()=>setDocuments(x=>x.filter((_,j)=>j!==i))}>×</button></div>)}<label className="privacy-check"><input type="checkbox"/> Tôi xác nhận tài liệu không chứa dữ liệu cá nhân/nhạy cảm của học sinh.</label><p className="privacy-note">Tài liệu được gửi trực tiếp đến Google Gemini để xử lý. Không tải lên dữ liệu cá nhân khi chưa được phép.</p><label>Nội dung bổ sung hoặc trích đoạn nguồn<textarea value={form.notes} onChange={set("notes")} rows={3} placeholder="Dán phân phối chương trình, yêu cầu riêng hoặc nội dung cần khóa nguồn…"/></label>
 <details className="api-panel" open><summary>Kết nối Gemini bằng khóa API <small>để AI đọc sâu tài liệu và soạn bài tự động</small></summary><div className="api-body"><ol><li>Bấm <a href="https://aistudio.google.com/app/apikey" target="_blank" rel="noreferrer">lấy mã miễn phí tại đây ↗</a>.</li><li>Bấm <b>Create API key</b>, rồi sao chép.</li><li>Dán mã vào ô bên dưới.</li></ol><label>Khóa API Gemini – thông tin bí mật</label><div className="key-row"><input value={apiKey} onChange={e=>setApiKey(e.target.value)} type={showKey?"text":"password"} placeholder="Dán khóa API từ Google AI Studio"/><button onClick={()=>setShowKey(x=>!x)}>{showKey?"Ẩn":"Hiện"}</button><button onClick={()=>setApiKey("")}>Xóa</button></div><label>Phong cách bài soạn<select value={style} onChange={e=>setStyle(e.target.value)}><option>Đầy đủ, chi tiết</option><option>Gọn, dễ triển khai</option><option>Tích cực, sáng tạo</option></select></label><details className="advanced"><summary>Tùy chọn nâng cao</summary><div className="model-row"><select value={model} onChange={e=>setModel(e.target.value)}><option value="auto">Tự động dò mô hình phù hợp</option>{models.map(m=><option key={m.name} value={m.name}>{m.displayName||m.name}</option>)}</select><button onClick={scan}>Dò lại</button></div><p>{modelStatus}</p></details></div></details><button className="generate" onClick={generate} disabled={busy}>{busy?"Đang xử lý…":"✦ Soạn kế hoạch bài dạy"}</button></div></section>
 <section className="panel result-panel" ref={previewRef}><div className="panel-title result-title"><b><i>03</i> Bản kế hoạch</b>{lesson&&<div className="result-actions"><button onClick={runAudit}>Kiểm định</button><button onClick={()=>doExport("pptx")} disabled={!!exporting}>PPTX</button><button onClick={()=>doExport("docx")} disabled={!!exporting}>Word</button><button onClick={()=>doExport("pdf")} disabled={!!exporting}>PDF</button></div>}</div>{!lesson?<div className="empty-state"><div className="paper-icon"><span/><span/><span/></div><h2>Kế hoạch bài dạy sẽ xuất hiện tại đây</h2><p>Điền thông tin bên trái, thêm tài liệu nguồn và bấm “Soạn kế hoạch bài dạy”.</p><div><span>✓ Bám CT GDPT 2018</span><span>✓ Tiến trình 4 bước</span><span>✓ NLS &amp; NLAI</span><span>✓ Xuất Word/PPTX/PDF</span></div></div>:<div className="document"><div className="doc-head"><small>BẢN KẾ HOẠCH</small><h2>{lesson.title}</h2><span>{lesson.subject} · Lớp {lesson.grade}</span></div>{audit.length>0&&<div className="audit-box">{audit.map((a,i)=><p className={a.level} key={i}><b>{a.level==="error"?"LỖI":a.level==="warning"?"CẢNH BÁO":"ĐẠT"}</b> {a.message}</p>)}</div>}{lesson.sections.map((s,i)=><article key={i}><h3><em>{String(i+1).padStart(2,"0")}</em>{s.heading}</h3><p>{s.content}</p><div className="visual-grid">{s.visuals?.map((v,j)=><div className={`visual-card ${v.type}`} key={j}><MathVisual visual={v}/></div>)}</div></article>)}<details className="json-editor"><summary>Visual Specification JSON</summary><textarea value={source} onChange={e=>setSource(e.target.value)} rows={14}/><button onClick={renderJson}>Dựng lại từ JSON</button></details></div>}</section>
 </div><div className="bottom-status">{message}</div></main>}
