"use client";
import katex from "katex";
import type {GraphVisual,SignVisual,VariationVisual,Visual} from "@/lib/types";

const MathText=({value,display=false}:{value:string;display?:boolean})=><span className={display?"math display":"math"} dangerouslySetInnerHTML={{__html:katex.renderToString(value,{throwOnError:false,displayMode:display,strict:"ignore"})}}/>;

function VariationTable({v}:{v:VariationVisual}){const n=Math.max(v.x.length,v.values.length);return <div className="math-table" role="img" aria-label="Bảng biến thiên"><div className="row"><b>x</b>{v.x.map((x,i)=><MathText key={i} value={x}/>)}</div><div className="row derivative"><b>y&apos;</b>{Array.from({length:n},(_,i)=><MathText key={i} value={v.derivative[i]??""}/>)}</div><div className="row variation"><b>y</b>{v.values.map((x,i)=><div className="trend" key={i}><MathText value={x}/>{i<v.values.length-1&&<span className={(Number(v.values[i+1])||0)>=(Number(x)||0)?"up":"down"}>↗</span>}</div>)}</div></div>}
function SignChart({v}:{v:SignVisual}){return <div className="math-table sign"><div className="row"><b>x</b>{v.x.map((x,i)=><MathText key={i} value={x}/>)}</div><div className="row"><b>{v.label||"f(x)"}</b>{v.signs.map((x,i)=><MathText key={i} value={x}/>)}</div></div>}

function safeEval(expr:string,x:number){if(!/^[0-9x+\-*/^().\s]+$/i.test(expr))return NaN;try{return Number(Function("x",`"use strict";return (${expr.replaceAll("^","**")})`)(x))}catch{return NaN}}
function Graph({v}:{v:GraphVisual}){const W=640,H=360,p=34;const sx=(x:number)=>p+(x-v.xMin)*(W-2*p)/(v.xMax-v.xMin);const sy=(y:number)=>H-p-(y-v.yMin)*(H-2*p)/(v.yMax-v.yMin);let paths:string[]=[];let current="";for(let i=0;i<=700;i++){const x=v.xMin+(v.xMax-v.xMin)*i/700,y=safeEval(v.expression,x);if(!Number.isFinite(y)||y<v.yMin*4||y>v.yMax*4){if(current)paths.push(current);current="";continue}current+=(current?" L ":"M ")+`${sx(x).toFixed(2)} ${sy(y).toFixed(2)}`}if(current)paths.push(current);return <svg className="graph" viewBox={`0 0 ${W} ${H}`} role="img" aria-label={`Đồ thị ${v.expression}`}><rect width={W} height={H} rx="14" fill="#fff"/><g stroke="#dbe5ee" strokeWidth="1">{Array.from({length:9},(_,i)=><line key={`h${i}`} x1={p} x2={W-p} y1={p+i*(H-2*p)/8} y2={p+i*(H-2*p)/8}/>)}{Array.from({length:13},(_,i)=><line key={`v${i}`} y1={p} y2={H-p} x1={p+i*(W-2*p)/12} x2={p+i*(W-2*p)/12}/>)}</g><g stroke="#263746" strokeWidth="1.5"><line x1={p} x2={W-p} y1={sy(0)} y2={sy(0)}/><line y1={p} y2={H-p} x1={sx(0)} x2={sx(0)}/></g>{v.asymptotes?.map((a,i)=><line key={i} stroke="#e56b6f" strokeDasharray="7 6" x1={a.kind==="vertical"?sx(a.value):p} x2={a.kind==="vertical"?sx(a.value):W-p} y1={a.kind==="horizontal"?sy(a.value):p} y2={a.kind==="horizontal"?sy(a.value):H-p}/>)}{paths.map((d,i)=><path key={i} d={d} fill="none" stroke="#087e8b" strokeWidth="3"/>)}{v.points?.map((q,i)=><g key={i}><circle cx={sx(q.x)} cy={sy(q.y)} r="5" fill="#ef8354"/><text x={sx(q.x)+8} y={sy(q.y)-8}>{q.label||`(${q.x};${q.y})`}</text></g>)}</svg>}
export function MathVisual({visual}:{visual:Visual}){if(visual.type==="formula")return <MathText value={visual.latex} display={visual.display??true}/>;if(visual.type==="variation_table")return <VariationTable v={visual}/>;if(visual.type==="sign_chart")return <SignChart v={visual}/>;return <Graph v={visual}/>}
